Add `disabled` key
This is useful for conditionally disabling based on some environment
variable spliced into a plugin.yml, such as whether we're using `rr` or
not on CI.

diff --git a/.buildkite/pipeline.yml b/.buildkite/pipeline.yml
--- a/.buildkite/pipeline.yml
+++ b/.buildkite/pipeline.yml
@@ -17,6 +17,19 @@ steps:
       # Create a sub-bash and kill it, then ignore its failure
       bash -c 'kill -11 $$$$' || true
 
+  - label: ":boom: :unamused: disabled coredumps"
+    key: disabled-coredumps
+    plugins:
+      - ".buildkite/plugins/coreupload":
+          core_pattern: "*.core"
+          disabled: "true"
+    commands: |
+      # Enable core dumping
+      ulimit -c unlimited
+
+      # Create a sub-bash and kill it, then ignore its failure
+      bash -c 'kill -11 $$$$' || true
+
   - label: ":boom: :zipper_mouth_face: zstd coredumps"
     key: gen-zstd-coredumps
     plugins:
@@ -54,14 +67,18 @@ steps:
       echo "--- segfault 2"
       julia -e 'ccall(Ptr{UInt8}(rand(UInt64)), Cint, ())' || true
 
-  # Ensure that we got two coredumps from the previous run
+  # Ensure that we got two coredumps from the previous runs
   - label: "Ensure coredumps were uploaded"
     depends_on:
       - gen-zstd-coredumps
       - gen-raw-coredumps
+      - disabled-coredumps
     commands: |
       # Download all artifacts, ensure they match what we expect
       buildkite-agent artifact download '*.core*' .
+
+      [[ "$$(ls *.core* | wc -l)" == "3" ]]
+      echo "Three corefiles overall: ✔️"
 
       [[ "$$(ls julia-*.core.zst | wc -l)" == "2" ]]
       echo "Two zstd julia corefiles: ✔️"
